
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{list{id,text,done}}"
}

###

POST http://localhost:8080/graphql
Content-Type: application/graphql

query {list{id,text,done}}

###

POST http://localhost:8080/graphql
Content-Type: application/graphql

query {
   lastTodo{
      id,
      text,
      done
   }
}

###

POST http://localhost:8080/graphql
Content-Type: application/graphql

query {todo(id:"964886e9-9e0c-4356-a775-b9085a8b53e4"){id,text,done}}

###

POST http://localhost:8080/graphql
Content-Type: application/graphql

mutation {create(text:"Run all queries5"){id,text,done}}

###

POST http://localhost:8080/graphql
Content-Type: application/graphql

query GetTypeDetails{
  __type(name: "RootQuery") {
    name
    fields {
      name
      type {
        name
        kind
        ofType {
          name
          kind
        }
      }
    }
  }
}