package dao

import (
	"database/sql"
	"fmt"
	"github.com/iproduct/coursego/modules/model"
	"log"
)

type userRepoMysql struct {
	db *sql.DB
}

//FindAll returns all users
func (r *userRepoMysql) Find(start, count int) ([]model.User, error) {
	statement := "SELECT id, name, email, password, age FROM users LIMIT ? OFFSET ?"
	rows, err := r.db.Query(statement, count, start)

	if err != nil {
		return nil, err
	}

	defer rows.Close()

	users := []model.User{}

	for rows.Next() {
		var user model.User
		if err := rows.Scan(&user.ID, &user.Name, &user.Email, &user.Password, &user.Age); err != nil {
			return nil, err
		}
		users = append(users, user)
	}

	return users, nil
	//return nil, errors.New("Not implemented")
}

//FindById return users by user ID or error otherwise
func (r *userRepoMysql) FindByID(id int) (*model.User, error) {
	user := &model.User{}
	statement := "SELECT id, name, email, password, age FROM users WHERE id=?"
	err := r.db.QueryRow(statement, id).Scan(&user.ID, &user.Name, &user.Email, &user.Password, &user.Age)
	if err != nil {
		return nil, err
	}
	return user, nil
	//return nil, errors.New("Not implemented")
}

//FindByEmail returns a single user by user's email or error otherwise
func (r *userRepoMysql) FindByEmail(email string) (*model.User, error) {
	user := &model.User{}
	statement := "SELECT id, name, email, password, age FROM users WHERE email=?"
	err := r.db.QueryRow(statement, email).Scan(&user.ID, &user.Name, &user.Email, &user.Password, &user.Age)
	if err != nil {
		return nil, err
	}
	return user, nil
}

//Create creates and returns new user with autogenerated ID
func (r *userRepoMysql) Create(user *model.User) (*model.User, error) {
	statement := "INSERT INTO users(name, email, password, age) VALUES(?, ?, ?, ?)"
	result, err := r.db.Exec(statement, user.Name, user.Email, user.Password, user.Age)

	if err != nil {
		return nil, err
	}

	id, err := result.LastInsertId()
	user.ID = int(id)
	//err = r.db.QueryRow("SELECT LAST_INSERT_ID()").Scan(&user.ID)
	if err != nil {
		return nil, err
	}

	return user, nil
	//return nil, errors.New("Not implemented")
}

//Update updates existing user data
func (r *userRepoMysql) Update(user *model.User) (*model.User, error) {
	statement := "UPDATE users SET name=?, email=?, password=?, age=? WHERE id=?"
	_, err := r.db.Exec(statement, user.Name, user.Email, user.Password, user.Age, user.ID)
	return user, err
	//return nil, errors.New("Not implemented")
}

//DeleteById removes and returns user with specified ID or error otherwise
func (r *userRepoMysql) DeleteByID(id int) (*model.User, error) {
	user, err := r.FindByID(id)
	statement := "DELETE FROM users WHERE id=?"
	_, err = r.db.Exec(statement, id)
	return user, err
	//return nil, errors.New("Not implemented")
}

// NewMysql is a UserRepo constructor
func NewMysql(user, password, dbname string) UserRepo {
	repo := &userRepoMysql{}
	var err error
	connectionString := fmt.Sprintf("%s:%s@/%s", user, password, dbname)
	repo.db, err = sql.Open("mysql", connectionString)
	if err != nil {
		log.Fatal(err)
	}
	return repo
}
