
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query LatestPost {\n  latestPost\n  postsCount\n}"
}

###

POST http://localhost:8080/graphql
Content-Type: application/graphql

query Root{ latestPost, postsCount }

###
