// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: mathmax.proto

package mathmax

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *IntRequest) Reset() {
	*x = IntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mathmax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntRequest) ProtoMessage() {}

func (x *IntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mathmax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntRequest.ProtoReflect.Descriptor instead.
func (*IntRequest) Descriptor() ([]byte, []int) {
	return file_mathmax_proto_rawDescGZIP(), []int{0}
}

func (x *IntRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type IntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *IntResponse) Reset() {
	*x = IntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mathmax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntResponse) ProtoMessage() {}

func (x *IntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mathmax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntResponse.ProtoReflect.Descriptor instead.
func (*IntResponse) Descriptor() ([]byte, []int) {
	return file_mathmax_proto_rawDescGZIP(), []int{1}
}

func (x *IntResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_mathmax_proto protoreflect.FileDescriptor

var file_mathmax_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x68, 0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x1f, 0x0a, 0x0b, 0x49, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x32, 0x40, 0x0a, 0x04, 0x4d, 0x61,
	0x74, 0x68, 0x12, 0x38, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x67, 0x6f, 0x2f, 0x31, 0x30, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x6d, 0x61, 0x78,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mathmax_proto_rawDescOnce sync.Once
	file_mathmax_proto_rawDescData = file_mathmax_proto_rawDesc
)

func file_mathmax_proto_rawDescGZIP() []byte {
	file_mathmax_proto_rawDescOnce.Do(func() {
		file_mathmax_proto_rawDescData = protoimpl.X.CompressGZIP(file_mathmax_proto_rawDescData)
	})
	return file_mathmax_proto_rawDescData
}

var file_mathmax_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mathmax_proto_goTypes = []interface{}{
	(*IntRequest)(nil),  // 0: protobuf.IntRequest
	(*IntResponse)(nil), // 1: protobuf.IntResponse
}
var file_mathmax_proto_depIdxs = []int32{
	0, // 0: protobuf.Math.Max:input_type -> protobuf.IntRequest
	1, // 1: protobuf.Math.Max:output_type -> protobuf.IntResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mathmax_proto_init() }
func file_mathmax_proto_init() {
	if File_mathmax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mathmax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mathmax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mathmax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mathmax_proto_goTypes,
		DependencyIndexes: file_mathmax_proto_depIdxs,
		MessageInfos:      file_mathmax_proto_msgTypes,
	}.Build()
	File_mathmax_proto = out.File
	file_mathmax_proto_rawDesc = nil
	file_mathmax_proto_goTypes = nil
	file_mathmax_proto_depIdxs = nil
}
