package dao

import (
	"database/sql"
	"errors"
	"github.com/iproduct/coursego/modules/model"
)

type userRepoMysql struct {
	db *sql.DB
}

//FindAll returns all users
func (r *userRepoMysql) FindAll() ([]model.User, error) {
	return nil, errors.New("Not implemented")
}

//FindById return users by user ID or error otherwise
func (r *userRepoMysql) FindByID(id int) (*model.User, error) {
	return nil, errors.New("Not implemented")
}

//Create creates and returns new user with autogenerated ID
func (r *userRepoMysql) Create(user *model.User) (*model.User, error) {
	return nil, errors.New("Not implemented")
}

//Update updates existing user data
func (r *userRepoMysql) Update(user *model.User) (*model.User, error) {
	return nil, errors.New("Not implemented")
}

//DeleteById removes and returns user with specified ID or error otherwise
func (r *userRepoMysql) DeleteByID(id int) (*model.User, error) {
	return nil, errors.New("Not implemented")
}

// NewMysql is a UserRepo constructor
func NewMysql() *userRepoMysql {
	return &userRepoMysql{db: nil}
}
