package dao

import (
	"github.com/iproduct/coursego/modules/model"
)

type userRepo struct {
	users map[int]model.User
}

//FindAll returns all users
func (r *userRepo) FindAll() ([]model.User, error) {
	return nil, errors.New("Not implemented")
}

//FindById return users by user ID or error otherwise
func (r *userRepo) FindByID(id int) (model.User, error) {
	return nil, errors.New("Not implemented")
}

//Create creates and returns new user with autogenerated ID
func (r *userRepo) Create(user *model.User) (model.User, error) {
	return nil, errors.New("Not implemented")
}

//Update updates existing user data
func (r *userRepo) Update(user *model.User) (model.User, error) {
	return nil, errors.New("Not implemented")
}

//DeleteById removes and returns user with specified ID or error otherwise
func (r *userRepo) DeleteByID(id int) (model.User, error) {
	return nil, errors.New("Not implemented")
}

// New is a UserRepo constructor
func New() *UserRepo {
	return &userRepo{users: make(map[int]model.User)}
}
